#+TITLE: POS: Preface
#+SUBTITLE: The impossiblity of writing a preface

Hegel claims that it is misleading and even inappropriate to write a preface to
a philosophical work. Since prefaces usually state aims and results, which is
not doing doing philosophy. He believes that the subject-matter of philosophy is
total understanding of everything. Thus a preface to a philosophical work has to
be itself philosophical.

* How not to do philosophy?
- having encyclopeadic information of all philosophers is not adequate
  (e.g. memorizing wikipedia is not the same as possessing the knowledge of a
  subject ) 
- having a general overviews of the various schools of thought
- seeing different schools of thought as agreeing or disagreeing with each other
- justifying a new work philosopy as a contingent (historical) product
- oversimplifying cannot lead to truth

* How does one go about doing philosophy?
- understanding philosophical systems as gradual unfolding of truth and not as a
  series of disagreements. 
- understanding the contradictions between sytems and the progression of thought
  as neccessary, as part of a natural organic whole.
- real thought requires struggle. One has to spend time applying the universals
  to particular concrete cases. In doing so we will see messy things get and we
  unravel the interdependence of the Universal and the Particular. 
